"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { 
  X, MessageCircle, ShieldCheck, Loader2, BellRing, Hash, MessageSquare 
} from "lucide-react";
import MasterDialog from "@/lib/components/MasterDialog"; // Ensure this import is correct

// --- 🔔 COMPONENT 1: Notification Icon for Device Cards ---
export function RequestNotification({ deviceSn, pendingRequests, onClick }: { deviceSn: string, pendingRequests: any[], onClick: () => void }) {
  const hasRequest = pendingRequests.some(r => r.device_sn === deviceSn);
  if (!hasRequest) return null;

  return (
    <button 
      onClick={(e) => { e.stopPropagation(); onClick(); }} 
      className="absolute left-5 top-5 text-red-600 hover:scale-110 active:scale-90 transition-transform z-[20] p-1"
    >
      <BellRing size={22} className="animate-pulse" />
      <span className="absolute top-0 right-0 flex h-2.5 w-2.5">
        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
        <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-red-600 border border-white"></span>
      </span>
    </button>
  );
}

// --- 🛡️ COMPONENT 2: Main Tasks Manager Modal ---
export default function RequestManagerModal({ isOpen, onClose, onRefresh, filterSn }: { isOpen: boolean, onClose: () => void, onRefresh: () => void, filterSn?: string | null }) {
  const [requests, setRequests] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [dialog, setDialog] = useState({ isOpen: false, title: "", message: "", type: "info" as any });

  useEffect(() => { if (isOpen) fetchRequests(); }, [isOpen, filterSn]);

  const fetchRequests = async () => {
    setLoading(true);
    try {
      let query = supabase.from("requests").select("*").eq("status", "pending");
      if (filterSn) query = query.eq("device_sn", filterSn);
      const { data: reqData } = await query.order("created_at", { ascending: false });

      if (reqData?.length) {
        const { data: devData } = await supabase
          .from("devices")
          .select("device_sn, user_pass, user_name")
          .in("device_sn", reqData.map(r => r.device_sn));

        setRequests(reqData.map(req => ({ 
          ...req, 
          deviceDetails: devData?.find(d => d.device_sn === req.device_sn) 
        })));
      } else {
        setRequests([]);
      }
    } catch (err) { console.error(err); } 
    finally { setLoading(false); }
  };

  // 🛠️ Portal ID Generator Logic
  const generatePortalId = (sn: string) => {
    if (!sn || sn.length < 8) return "ME_ADMIN";
    return `ME_${sn.slice(-8).slice(0, 4).toLowerCase()}`;
  };

  // ✅ Handle WhatsApp Send & Complete Action
const handleAction = async (req: any) => {
    try {
      // 1. Mark as done in Database
      const { error } = await supabase.from("requests").update({ status: 'done' }).eq("id", req.id);
      if (error) throw error;

      // 2. Data Formatting
      const portalId = generatePortalId(req.device_sn);
      const userNote = req.message ? `\n\n*Note:* ${req.message}` : "";
      
      // 🚩 Clean String with proper New Lines
      const rawMsg = 
        `*🔐 CCTV ACCESS DETAILS*\n\n` +
        `📍 *Site:* ${req.site_name}\n` +
        `🆔 *Portal ID:* ${portalId}\n` +
        `👤 *User Name:* user\n` +
        `🛡️ *User Pass:* ${req.deviceDetails?.user_pass || 'N/A'}\n\n` +
        `_Generated by MODERN ENTERPRISES_`;

      // ✅ Proper Encoding for Emojis and Special Characters
      const encodedMsg = encodeURIComponent(rawMsg);

      // 3. Mobile Number Formatting (Ensure no + or spaces)
      const cleanMobile = req.mobile.replace(/\D/g, "");
      const finalMobile = cleanMobile.startsWith("91") ? cleanMobile : `91${cleanMobile}`;

      // 🚀 The API Link (More stable than wa.me for pre-filled text)
      const whatsappUrl = `https://api.whatsapp.com/send?phone=${finalMobile}&text=${encodedMsg}`;

      // 4. Execution
      window.open(whatsappUrl, '_blank');
      
      // 5. Cleanup UI
      fetchRequests(); 
      onRefresh();
      if (filterSn) onClose();

    } catch (err: any) { 
      setDialog({ 
        isOpen: true, 
        title: "Action Failed", 
        message: "WhatsApp dispatch failed. Please check your connection.", 
        type: "danger" 
      });
    }
  };

  if (!isOpen) return null;

  return (
    <>
      <div className="fixed inset-0 z-[200] flex items-end sm:items-center justify-center bg-slate-900/80 backdrop-blur-sm p-0 sm:p-4 animate-in fade-in">
        <div className="w-full max-w-2xl bg-white rounded-t-[40px] sm:rounded-[40px] shadow-2xl overflow-hidden border-t sm:border border-white animate-in slide-in-from-bottom duration-300 max-h-[92vh] flex flex-col">
          
          {/* Gradient Top Bar */}
          <div className="h-2.5 w-full bg-gradient-to-r from-blue-600 via-indigo-500 to-emerald-500 shrink-0"></div>

          {/* Header */}
          <div className="p-6 border-b flex justify-between items-center bg-white sticky top-0 z-10 shrink-0 text-left">
            <div>
              <h2 className="text-lg font-[1000] text-slate-900 uppercase italic flex items-center gap-2 tracking-tighter leading-none">
                <ShieldCheck className="text-blue-600" size={22} /> Tasks Manager
              </h2>
              <p className="text-[9px] font-black text-slate-400 uppercase tracking-[2px] mt-1.5">Manage Access Requests</p>
            </div>
            <button onClick={onClose} className="p-2.5 bg-slate-50 rounded-2xl text-slate-400 active:scale-90 border transition-all">
              <X size={20} strokeWidth={3} />
            </button>
          </div>

          {/* Request List Body */}
          <div className="p-4 overflow-y-auto space-y-4 bg-slate-50/50 flex-1 pb-16">
            {loading ? (
              <div className="flex flex-col items-center py-20 gap-3">
                <Loader2 className="animate-spin text-blue-600" size={32}/>
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Syncing Cloud...</p>
              </div>
            ) : requests.length === 0 ? (
              <div className="text-center py-20 opacity-20 flex flex-col items-center gap-4">
                <BellRing size={48} />
                <p className="font-black text-[10px] uppercase tracking-[5px]">No Pending Requests</p>
              </div>
            ) : (
              requests.map(req => (
                <div key={req.id} className="p-5 rounded-[35px] border border-slate-200 bg-white shadow-sm active:border-blue-200 transition-all text-left">
                  
                  <div className="flex items-start justify-between gap-4 mb-4">
                    <h3 className="text-base font-[1000] text-slate-900 uppercase italic leading-tight">{req.site_name}</h3>
                    <span className="text-[9px] font-black text-slate-500 bg-slate-100 px-3 py-1 rounded-xl border uppercase">SN: {req.device_sn}</span>
                  </div>

                  {req.message && (
                    <div className="flex items-start gap-3 bg-yellow-50 p-4 rounded-2xl border border-yellow-100">
                    <MessageSquare size={16} className="text-yellow-600 shrink-0 mt-0.5" />
                    <p className="text-xs font-bold text-yellow-900 leading-snug italic">"{req.message}"</p>
                  </div>
                  )}

                  <div className="flex flex-wrap items-center justify-between gap-4 pt-5 border-t border-slate-50">
                    <div className="flex items-center gap-4">
                      <div className="flex flex-col">
                        <span className="text-[8px] font-black text-blue-500 uppercase tracking-widest leading-none">Portal ID</span>
                        <span className="text-xs font-black text-slate-800 mt-2 uppercase italic tracking-tighter">{generatePortalId(req.device_sn)}</span>
                      </div>
                      <div className="flex flex-col border-l pl-4">
                      <span className="text-[8px] font-black text-slate-400 uppercase">WhatsApp</span>
                      <span className="text-xs font-bold text-slate-800">{req.mobile}</span>
                    </div>
                    </div>
                    
                    <button 
                      onClick={() => handleAction(req)} 
                      className="w-full sm:w-auto bg-green-600 text-white px-8 py-4 rounded-[25px] flex items-center justify-center gap-3 text-[11px] font-[1000] uppercase tracking-widest shadow-xl shadow-green-100 active:scale-95 transition-all"
                    >
                      <MessageCircle size={18}/> Send & Complete
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* 🛡️ Master Dialog Integration */}
      <MasterDialog 
        isOpen={dialog.isOpen} 
        onClose={() => setDialog(prev => ({ ...prev, isOpen: false }))} 
        onConfirm={() => setDialog(prev => ({ ...prev, isOpen: false }))} 
        title={dialog.title} 
        message={dialog.message} 
        type={dialog.type} 
        confirmText="Understood" 
      />
    </>
  );
}